openapi: 3.0.0
info:
  title: Price Service API
  description: API for querying product prices based on date, product ID, and brand ID.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /prices:
    get:
      summary: Get price for a product
      parameters:
        - in: query
          name: applicationDate
          schema:
            type: string
            format: date-time
          required: true
          description: The date and time for which the price should be applied.
        - in: query
          name: productId
          schema:
            type: integer
          required: true
          description: The ID of the product.
        - in: query
          name: brandId
          schema:
            type: integer
          required: true
          description: The ID of the brand (chain).
      responses:
        '200':
          description: Price information
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: integer
                  brandId:
                    type: integer
                  priceList:
                    type: integer
                  startDate:
                    type: string
                    format: date-time
                  endDate:
                    type: string
                    format: date-time
                  price:
                    type: number
                    format: double
                  currency:
                    type: string
        '404':
          description: Price not found for given parameters
        '500':
          description: Internal server error